# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x0e\n\x0c\x45mptyBooking\";\n\nAddBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t\"\x18\n\x06UserId\x12\x0e\n\x06userid\x18\x01 \x01(\t\"(\n\x08\x44\x61teItem\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"8\n\x0c\x42ookingsUser\x12\x18\n\x05\x64\x61tes\x18\x01 \x03(\x0b\x32\t.DateItem\x12\x0e\n\x06userid\x18\x02 \x01(\t2\x9d\x01\n\x07\x42ooking\x12,\n\x08get_json\x12\r.EmptyBooking\x1a\r.BookingsUser\"\x00\x30\x01\x12\x30\n\x14get_booking_for_user\x12\x07.UserId\x1a\r.BookingsUser\"\x00\x12\x32\n\x12\x61\x64\x64_booking_byuser\x12\x0b.AddBooking\x1a\r.BookingsUser\"\x00\x62\x06proto3')



_EMPTYBOOKING = DESCRIPTOR.message_types_by_name['EmptyBooking']
_ADDBOOKING = DESCRIPTOR.message_types_by_name['AddBooking']
_USERID = DESCRIPTOR.message_types_by_name['UserId']
_DATEITEM = DESCRIPTOR.message_types_by_name['DateItem']
_BOOKINGSUSER = DESCRIPTOR.message_types_by_name['BookingsUser']
EmptyBooking = _reflection.GeneratedProtocolMessageType('EmptyBooking', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:EmptyBooking)
  })
_sym_db.RegisterMessage(EmptyBooking)

AddBooking = _reflection.GeneratedProtocolMessageType('AddBooking', (_message.Message,), {
  'DESCRIPTOR' : _ADDBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:AddBooking)
  })
_sym_db.RegisterMessage(AddBooking)

UserId = _reflection.GeneratedProtocolMessageType('UserId', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:UserId)
  })
_sym_db.RegisterMessage(UserId)

DateItem = _reflection.GeneratedProtocolMessageType('DateItem', (_message.Message,), {
  'DESCRIPTOR' : _DATEITEM,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:DateItem)
  })
_sym_db.RegisterMessage(DateItem)

BookingsUser = _reflection.GeneratedProtocolMessageType('BookingsUser', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGSUSER,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingsUser)
  })
_sym_db.RegisterMessage(BookingsUser)

_BOOKING = DESCRIPTOR.services_by_name['Booking']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYBOOKING._serialized_start=17
  _EMPTYBOOKING._serialized_end=31
  _ADDBOOKING._serialized_start=33
  _ADDBOOKING._serialized_end=92
  _USERID._serialized_start=94
  _USERID._serialized_end=118
  _DATEITEM._serialized_start=120
  _DATEITEM._serialized_end=160
  _BOOKINGSUSER._serialized_start=162
  _BOOKINGSUSER._serialized_end=218
  _BOOKING._serialized_start=221
  _BOOKING._serialized_end=378
# @@protoc_insertion_point(module_scope)
