# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import booking_pb2 as booking__pb2


class BookingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_json = channel.unary_stream(
                '/Booking/get_json',
                request_serializer=booking__pb2.EmptyBooking.SerializeToString,
                response_deserializer=booking__pb2.BookingsUser.FromString,
                )
        self.get_booking_for_user = channel.unary_unary(
                '/Booking/get_booking_for_user',
                request_serializer=booking__pb2.UserId.SerializeToString,
                response_deserializer=booking__pb2.BookingsUser.FromString,
                )
        self.add_booking_byuser = channel.unary_unary(
                '/Booking/add_booking_byuser',
                request_serializer=booking__pb2.AddBooking.SerializeToString,
                response_deserializer=booking__pb2.BookingsUser.FromString,
                )


class BookingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_json(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_booking_for_user(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_booking_byuser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_json': grpc.unary_stream_rpc_method_handler(
                    servicer.get_json,
                    request_deserializer=booking__pb2.EmptyBooking.FromString,
                    response_serializer=booking__pb2.BookingsUser.SerializeToString,
            ),
            'get_booking_for_user': grpc.unary_unary_rpc_method_handler(
                    servicer.get_booking_for_user,
                    request_deserializer=booking__pb2.UserId.FromString,
                    response_serializer=booking__pb2.BookingsUser.SerializeToString,
            ),
            'add_booking_byuser': grpc.unary_unary_rpc_method_handler(
                    servicer.add_booking_byuser,
                    request_deserializer=booking__pb2.AddBooking.FromString,
                    response_serializer=booking__pb2.BookingsUser.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Booking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Booking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_json(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Booking/get_json',
            booking__pb2.EmptyBooking.SerializeToString,
            booking__pb2.BookingsUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_booking_for_user(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/get_booking_for_user',
            booking__pb2.UserId.SerializeToString,
            booking__pb2.BookingsUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_booking_byuser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/add_booking_byuser',
            booking__pb2.AddBooking.SerializeToString,
            booking__pb2.BookingsUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
